/* ================================================================
   Full emoji dataset for the searchable emoji picker (icons.js).
   Each item is [emoji, "searchable keywords"]. Grouped into the same
   broad categories the OS emoji picker uses, browsable without a
   search term or filterable by typing (English keywords).
================================================================ */

const EMOJI_FULL_DATA = [
{ cat: 'Smilefjes & følelser', items: [
['😀','grinning face smile happy'],['😃','grinning face big eyes smile happy joy'],
['😄','grinning smiling eyes happy joy laugh'],['😁','beaming face grin smile happy'],
['😆','grinning squinting laugh haha'],['😅','grinning sweat laugh relief'],
['🤣','rolling floor laughing rofl lol'],['😂','face tears joy laugh cry lol'],
['🙂','slightly smiling face smile'],['🙃','upside down face silly'],
['😉','winking face wink'],['😊','smiling face blush happy'],
['😇','innocent halo angel'],['🥰','smiling hearts love adore'],
['😍','heart eyes love crush'],['🤩','star struck excited amazed'],
['😘','face blowing kiss love'],['😗','kissing face'],
['😚','kissing closed eyes'],['😙','kissing smiling eyes'],
['😋','face savoring food yum delicious'],['😛','face tongue playful'],
['😜','winking tongue silly'],['🤪','zany crazy face'],
['😝','squinting tongue face'],['🤑','money mouth face rich dollar cash'],
['🤗','hugging face hug'],['🤭','face hand mouth oops giggle'],
['🤫','shushing face quiet secret'],['🤔','thinking face think hmm'],
['🤐','zipper mouth face silence quiet'],['🤨','raised eyebrow suspicious skeptical'],
['😐','neutral face meh'],['😑','expressionless face blank'],
['😶','no mouth face silent'],['😏','smirking face smug'],
['😒','unamused face annoyed'],['🙄','rolling eyes face annoyed'],
['😬','grimacing face awkward'],['🤥','lying face pinocchio nose'],
['😌','relieved face calm'],['😔','pensive face sad'],
['😪','sleepy face tired'],['🤤','drooling face'],
['😴','sleeping face zzz tired'],['😷','face medical mask sick'],
['🤒','face thermometer sick fever'],['🤕','face head bandage hurt injured'],
['🤢','nauseated face sick disgust'],['🤮','vomiting face sick throw up'],
['🤧','sneezing face sick'],['🥵','hot face heat sweating'],
['🥶','cold face freezing'],['🥴','woozy face dizzy drunk'],
['😵','dizzy face knocked out'],['🤯','exploding head mind blown shocked'],
['🤠','cowboy hat face'],['🥳','partying face celebrate party'],
['🥸','disguised face glasses mustache'],['😎','sunglasses cool face'],
['🤓','nerd face glasses smart'],['🧐','monocle face fancy inspect'],
['😕','confused face'],['😟','worried face'],
['🙁','slightly frowning face sad'],['☹️','frowning face sad'],
['😮','face open mouth surprised wow'],['😯','hushed face surprised'],
['😲','astonished face shocked wow'],['😳','flushed face embarrassed blush'],
['🥺','pleading face puppy eyes begging'],['😦','frowning open mouth face'],
['😧','anguished face'],['😨','fearful face scared'],
['😰','anxious face sweat worried'],['😥','sad relieved face'],
['😢','crying face tear sad'],['😭','loudly crying face sob sad'],
['😱','face screaming fear shocked scared'],['😖','confounded face'],
['😣','persevering face struggle'],['😞','disappointed face sad'],
['😓','downcast face sweat'],['😩','weary face tired'],
['😫','tired face exhausted'],['🥱','yawning face tired bored'],
['😤','face steam nose triumph angry'],['😡','pouting face angry mad rage'],
['😠','angry face mad'],['🤬','face symbols mouth swearing angry cursing'],
['😈','smiling face horns devil evil'],['👿','angry face horns devil'],
['💀','skull death'],['☠️','skull crossbones death danger'],
['💩','pile poo poop'],['🤡','clown face'],
['👹','ogre monster'],['👺','goblin monster'],
['👻','ghost halloween'],['👽','alien ufo'],
['👾','alien monster space invader game'],['🤖','robot face'],
['😺','grinning cat'],['😸','grinning cat smiling eyes'],
['😹','cat face tears joy laugh'],['😻','heart eyes cat love'],
['😼','cat wry smile smirk'],['😽','kissing cat'],
['🙀','weary cat scared'],['😿','crying cat sad'],['😾','pouting cat angry'],
]},
{ cat: 'Mennesker & kropp', items: [
['👋','waving hand hello hi bye'],['🤚','raised back hand'],
['🖐️','hand fingers splayed stop'],['✋','raised hand stop high five'],
['🖖','vulcan salute spock'],['👌','ok hand okay'],
['🤌','pinched fingers italian'],['🤏','pinching hand small little'],
['✌️','victory hand peace'],['🤞','crossed fingers luck'],
['🤟','love you gesture hand'],['🤘','sign horns rock'],
['🤙','call me hand shaka'],['👈','backhand index pointing left'],
['👉','backhand index pointing right'],['👆','backhand index pointing up'],
['👇','backhand index pointing down'],['☝️','index pointing up'],
['👍','thumbs up like good yes'],['👎','thumbs down dislike bad no'],
['✊','raised fist'],['👊','oncoming fist punch'],
['🤛','left facing fist'],['🤜','right facing fist'],
['👏','clapping hands applause'],['🙌','raising hands celebrate praise'],
['👐','open hands'],['🤲','palms together up pray'],
['🤝','handshake deal agreement'],['🙏','folded hands pray please thanks'],
['✍️','writing hand'],['💅','nail polish manicure'],
['🤳','selfie'],['💪','flexed biceps muscle strong'],
['🦾','mechanical arm'],['🦿','mechanical leg'],
['🦵','leg'],['🦶','foot'],['👂','ear hear'],
['🦻','ear hearing aid'],['👃','nose'],['🧠','brain mind smart'],
['🦷','tooth teeth dental'],['🦴','bone'],['👀','eyes look see'],
['👁️','eye'],['👅','tongue'],['👄','mouth lips'],
['👶','baby'],['🧒','child kid'],['👦','boy'],['👧','girl'],
['🧑','person adult'],['👱','person blond hair'],['👨','man'],
['🧔','person beard'],['👩','woman'],['🧓','older person'],
['👴','old man grandpa'],['👵','old woman grandma'],
['🙍','person frowning'],['🙎','person pouting'],
['🙅','person gesturing no'],['🙆','person gesturing ok'],
['💁','person tipping hand'],['🙋','person raising hand'],
['🧏','deaf person'],['🙇','person bowing'],
['🤦','person facepalm'],['🤷','person shrugging'],
['👮','police officer'],['🕵️','detective spy'],
['💂','guard'],['👷','construction worker'],
['🤴','prince'],['👸','princess'],['👳','person turban'],
['👲','person cap'],['🧕','woman headscarf'],
['🤵','person tuxedo'],['👰','person veil bride'],
['🤰','pregnant woman'],['🤱','breast feeding'],
['👼','baby angel'],['🎅','santa claus christmas'],
['🤶','mrs claus christmas'],['🦸','superhero'],
['🦹','supervillain'],['🧙','mage wizard'],['🧚','fairy'],
['🧛','vampire'],['🧜','mermaid'],['🧝','elf'],
['🧞','genie'],['🧟','zombie'],['💆','person massage spa'],
['💇','person haircut'],['🚶','person walking'],
['🧍','person standing'],['🧎','person kneeling'],
['🏃','person running'],['💃','woman dancing'],['🕺','man dancing'],
['🕴️','person suit levitating'],['👯','people bunny ears party'],
['🧖','person steamy room sauna'],['🧗','person climbing'],
['🤺','fencing sport'],['🏇','horse racing'],['⛷️','skier'],
['🏂','snowboarder'],['🏌️','golf'],['🏄','surfer'],
['🚣','rowing boat'],['🏊','swimmer'],['⛹️','person bouncing ball basketball'],
['🏋️','person lifting weights gym'],['🚴','person biking cycling'],
['🚵','person mountain biking'],['🤸','cartwheel gymnastics'],
['🤼','wrestling'],['🤽','water polo'],['🤾','handball'],
['🤹','juggling'],['🧘','person lotus position yoga meditate'],
['🛀','person taking bath'],['🛌','person bed sleep'],
]},
{ cat: 'Dyr & natur', items: [
['🐶','dog puppy pet'],['🐱','cat kitten pet'],['🐭','mouse'],
['🐹','hamster pet'],['🐰','rabbit bunny'],['🦊','fox'],
['🐻','bear'],['🐼','panda'],['🐨','koala'],['🐯','tiger'],
['🦁','lion'],['🐮','cow'],['🐷','pig'],['🐽','pig nose snout'],
['🐸','frog'],['🐵','monkey'],['🙈','monkey see no evil'],
['🙉','monkey hear no evil'],['🙊','monkey speak no evil'],
['🐒','monkey'],['🐔','chicken'],['🐧','penguin'],['🐦','bird'],
['🐤','baby chick'],['🐣','hatching chick'],['🐥','front facing baby chick'],
['🦆','duck'],['🦅','eagle'],['🦉','owl'],['🦇','bat'],
['🐺','wolf'],['🐗','boar'],['🐴','horse'],['🦄','unicorn'],
['🐝','bee honeybee'],['🐛','bug caterpillar'],['🦋','butterfly'],
['🐌','snail'],['🐞','lady beetle ladybug'],['🐜','ant'],
['🦟','mosquito'],['🦗','cricket'],['🕷️','spider'],['🕸️','spider web'],
['🦂','scorpion'],['🐢','turtle'],['🐍','snake'],['🦎','lizard'],
['🦖','t-rex dinosaur'],['🦕','sauropod dinosaur'],['🐙','octopus'],
['🦑','squid'],['🦐','shrimp'],['🦞','lobster'],['🦀','crab'],
['🐡','blowfish pufferfish'],['🐠','tropical fish'],['🐟','fish'],
['🐬','dolphin'],['🐳','spouting whale'],['🐋','whale'],
['🦈','shark'],['🐊','crocodile'],['🐅','tiger face'],
['🐆','leopard'],['🦓','zebra'],['🦍','gorilla'],
['🦧','orangutan'],['🐘','elephant'],['🦛','hippopotamus'],
['🦏','rhinoceros'],['🐪','camel'],['🐫','two hump camel'],
['🦒','giraffe'],['🦘','kangaroo'],['🐃','water buffalo'],
['🐂','ox bull'],['🐄','cow'],['🐎','horse'],['🐖','pig'],
['🐏','ram sheep'],['🐑','sheep ewe'],['🦙','llama'],
['🐐','goat'],['🦌','deer'],['🐕','dog'],['🐩','poodle dog'],
['🦮','guide dog'],['🐈','cat'],['🐓','rooster'],['🦃','turkey'],
['🦚','peacock'],['🦜','parrot'],['🦢','swan'],['🦩','flamingo'],
['🐇','rabbit'],['🦝','raccoon'],['🦨','skunk'],['🦡','badger'],
['🦦','otter'],['🦥','sloth'],['🐁','mouse'],['🐀','rat'],
['🐿️','chipmunk squirrel'],['🦔','hedgehog'],['🐾','paw prints'],
['🌵','cactus'],['🎄','christmas tree'],['🌲','evergreen tree'],
['🌳','deciduous tree'],['🌴','palm tree'],['🌱','seedling plant'],
['🌿','herb plant'],['☘️','shamrock clover'],['🍀','four leaf clover luck'],
['🎍','pine decoration'],['🎋','tanabata tree'],['🍃','leaf fluttering wind'],
['🍂','fallen leaf autumn'],['🍁','maple leaf'],['🍄','mushroom'],
['🐚','spiral shell'],['🌾','sheaf rice'],['💐','bouquet flowers'],
['🌷','tulip flower'],['🌹','rose flower'],['🥀','wilted flower'],
['🌺','hibiscus flower'],['🌸','cherry blossom flower'],
['🌼','blossom flower'],['🌻','sunflower'],['🌞','sun face'],
['🌝','full moon face'],['🌛','first quarter moon face'],
['🌜','last quarter moon face'],['🌚','new moon face'],
['🌕','full moon'],['🌖','waning gibbous moon'],['🌗','last quarter moon'],
['🌘','waning crescent moon'],['🌑','new moon'],['🌒','waxing crescent moon'],
['🌓','first quarter moon'],['🌔','waxing gibbous moon'],['🌙','crescent moon'],
['🌎','earth globe americas'],['🌍','earth globe africa europe'],
['🌏','earth globe asia australia'],['💫','dizzy star'],['⭐','star'],
['🌟','glowing star'],['✨','sparkles'],['⚡','lightning bolt'],
['☄️','comet'],['💥','collision boom'],['🔥','fire flame hot'],
['🌪️','tornado'],['🌈','rainbow'],['☀️','sun sunny'],
['🌤️','sun small cloud'],['⛅','sun behind cloud'],
['🌥️','sun behind large cloud'],['☁️','cloud'],
['🌦️','sun behind rain cloud'],['🌧️','cloud rain'],
['⛈️','cloud lightning rain storm'],['🌩️','cloud lightning'],
['❄️','snowflake snow'],['☃️','snowman'],['⛄','snowman without snow'],
['🌬️','wind face'],['💨','dashing away wind'],['💧','droplet water'],
['💦','sweat droplets water'],['☔','umbrella rain'],['🌊','water wave ocean'],
]},
{ cat: 'Mat & drikke', items: [
['🍏','green apple'],['🍎','red apple'],['🍐','pear'],
['🍊','tangerine orange'],['🍋','lemon'],['🍌','banana'],
['🍉','watermelon'],['🍇','grapes'],['🍓','strawberry'],
['🫐','blueberries'],['🍈','melon'],['🍒','cherries'],
['🍑','peach'],['🥭','mango'],['🍍','pineapple'],['🥥','coconut'],
['🥝','kiwi fruit'],['🍅','tomato'],['🍆','eggplant aubergine'],
['🥑','avocado'],['🥦','broccoli'],['🥬','leafy green lettuce'],
['🥒','cucumber'],['🌶️','hot pepper chili'],['🫑','bell pepper'],
['🌽','corn'],['🥕','carrot'],['🫒','olive'],['🧄','garlic'],
['🧅','onion'],['🥔','potato'],['🍠','sweet potato'],
['🥐','croissant'],['🥯','bagel'],['🍞','bread'],['🥖','baguette bread'],
['🥨','pretzel'],['🧀','cheese'],['🥚','egg'],['🍳','cooking fried egg'],
['🧈','butter'],['🥞','pancakes'],['🧇','waffle'],['🥓','bacon'],
['🥩','cut meat steak'],['🍗','poultry leg chicken'],['🍖','meat bone'],
['🌭','hot dog'],['🍔','hamburger burger'],['🍟','french fries'],
['🍕','pizza'],['🫓','flatbread'],['🥪','sandwich'],
['🥙','stuffed flatbread'],['🧆','falafel'],['🌮','taco'],
['🌯','burrito'],['🫔','tamale'],['🥗','green salad'],
['🥘','shallow pan food paella'],['🫕','fondue'],['🥫','canned food'],
['🍝','spaghetti pasta'],['🍜','steaming bowl ramen noodles'],
['🍲','pot food stew'],['🍛','curry rice'],['🍣','sushi'],
['🍱','bento box'],['🥟','dumpling'],['🦪','oyster'],
['🍤','fried shrimp tempura'],['🍙','rice ball'],['🍚','cooked rice'],
['🍘','rice cracker'],['🍥','fish cake'],['🥠','fortune cookie'],
['🥮','moon cake'],['🍢','oden skewer'],['🍡','dango'],
['🍧','shaved ice'],['🍨','ice cream'],['🍦','soft ice cream'],
['🥧','pie'],['🧁','cupcake'],['🍰','shortcake cake'],
['🎂','birthday cake'],['🍮','custard pudding'],['🍭','lollipop candy'],
['🍬','candy sweet'],['🍫','chocolate bar'],['🍿','popcorn'],
['🍩','doughnut donut'],['🍪','cookie'],['🌰','chestnut'],
['🥜','peanuts'],['🍯','honey pot'],['🥛','glass milk'],
['🍼','baby bottle'],['☕','hot beverage coffee'],['🍵','teacup tea'],
['🧃','beverage box juice'],['🥤','cup straw drink soda'],
['🧋','bubble tea'],['🍶','sake'],['🍺','beer mug'],
['🍻','clinking beer mugs'],['🥂','clinking glasses cheers champagne'],
['🍷','wine glass'],['🥃','tumbler glass whiskey'],['🍸','cocktail glass martini'],
['🍹','tropical drink'],['🧉','mate drink'],['🍾','bottle popping cork champagne'],
['🧊','ice cube'],
]},
{ cat: 'Aktivitet', items: [
['⚽','soccer ball football'],['🏀','basketball'],['🏈','american football'],
['⚾','baseball'],['🥎','softball'],['🎾','tennis'],['🏐','volleyball'],
['🏉','rugby football'],['🎱','pool 8 ball billiards'],['🪀','yo-yo'],
['🏓','ping pong table tennis'],['🏸','badminton'],['🏒','ice hockey'],
['🏑','field hockey'],['🥍','lacrosse'],['🏏','cricket bat ball'],
['🥅','goal net'],['⛳','flag hole golf'],['🪁','kite'],
['🏹','bow arrow'],['🎣','fishing pole fish'],['🤿','diving mask snorkel'],
['🥊','boxing glove'],['🥋','martial arts uniform'],['🎽','running shirt sash'],
['🛹','skateboard'],['🛼','roller skate'],['🛷','sled'],
['⛸️','ice skate'],['🥌','curling stone'],['🎿','skis'],
['🪂','parachute'],['🏆','trophy win award'],['🥇','gold medal first'],
['🥈','silver medal second'],['🥉','bronze medal third'],['🏅','sports medal'],
['🎖️','military medal'],['🏵️','rosette'],['🎗️','reminder ribbon'],
['🎫','ticket'],['🎟️','admission tickets'],['🎪','circus tent'],
['🎭','performing arts theater masks'],['🩰','ballet shoes'],
['🎨','artist palette paint'],['🎬','clapper board movie film'],
['🎤','microphone sing karaoke'],['🎧','headphone music'],
['🎼','musical score'],['🎹','musical keyboard piano'],['🥁','drum'],
['🎷','saxophone'],['🎺','trumpet'],['🎸','guitar'],['🪕','banjo'],
['🎻','violin'],['🎲','game die dice'],['♟️','chess pawn'],
['🎯','direct hit dart target'],['🎳','bowling'],['🎮','video game controller'],
['🎰','slot machine'],
]},
{ cat: 'Reise & steder', items: [
['🚗','car automobile'],['🚕','taxi cab'],['🚙','sport utility vehicle suv'],
['🚌','bus'],['🚎','trolleybus'],['🏎️','racing car'],['🚓','police car'],
['🚑','ambulance'],['🚒','fire engine truck'],['🚐','minibus van'],
['🛻','pickup truck'],['🚚','delivery truck'],['🚛','articulated lorry truck'],
['🚜','tractor'],['🛴','kick scooter'],['🚲','bicycle bike'],
['🛵','motor scooter'],['🏍️','motorcycle'],['🛺','auto rickshaw'],
['🚨','police car light siren'],['🚔','oncoming police car'],
['🚍','oncoming bus'],['🚘','oncoming automobile car'],['🚖','oncoming taxi'],
['🚡','aerial tramway'],['🚠','mountain cableway'],['🚟','suspension railway'],
['🚃','railway car'],['🚋','tram car'],['🚞','mountain railway'],
['🚝','monorail'],['🚄','high speed train'],['🚅','bullet train'],
['🚈','light rail'],['🚂','locomotive steam train'],['🚆','train'],
['🚇','metro subway'],['🚊','tram'],['🚉','station'],['✈️','airplane flight'],
['🛫','airplane departure'],['🛬','airplane arrival'],['🛩️','small airplane'],
['💺','seat airplane'],['🛰️','satellite'],['🚀','rocket launch'],
['🛸','flying saucer ufo'],['🚁','helicopter'],['🛶','canoe boat'],
['⛵','sailboat boat'],['🚤','speedboat'],['🛥️','motor boat'],
['🛳️','passenger ship'],['⛴️','ferry boat'],['🚢','ship boat'],
['⚓','anchor boat'],['⛽','fuel pump gas station'],['🚧','construction sign'],
['🚦','traffic light vertical'],['🚥','traffic light horizontal'],
['🚏','bus stop'],['🗺️','world map'],['🗿','moai statue'],
['🗽','statue liberty'],['🗼','tokyo tower'],['🏰','castle'],
['🏯','japanese castle'],['🏟️','stadium'],['🎡','ferris wheel'],
['🎢','roller coaster'],['🎠','carousel horse'],['⛱️','umbrella ground beach'],
['🏖️','beach umbrella'],['🏝️','desert island'],['🏜️','desert'],
['🌋','volcano'],['⛰️','mountain'],['🏔️','snow capped mountain'],
['🗻','mount fuji'],['🏕️','camping tent'],['⛺','tent'],
['🏠','house home'],['🏡','house garden home'],['🏘️','houses'],
['🏚️','derelict house'],['🏗️','building construction'],['🏭','factory'],
['🏢','office building'],['🏬','department store'],['🏣','japanese post office'],
['🏤','post office'],['🏥','hospital'],['🏦','bank'],['🏨','hotel'],
['🏪','convenience store'],['🏫','school'],['🏩','love hotel'],
['💒','wedding chapel'],['⛪','church'],['🕌','mosque'],
['🕍','synagogue'],['🛕','hindu temple'],['🕋','kaaba'],['⛩️','shinto shrine'],
]},
{ cat: 'Objekter', items: [
['⌚','watch time'],['📱','mobile phone'],['📲','mobile phone arrow'],
['💻','laptop computer'],['⌨️','keyboard'],['🖥️','desktop computer'],
['🖨️','printer'],['🖱️','computer mouse'],['🕹️','joystick game'],
['💽','computer disk'],['💾','floppy disk save'],['💿','optical disk cd'],
['📀','dvd'],['📷','camera photo'],['📸','camera flash photo'],
['📹','video camera'],['🎥','movie camera film'],['📽️','film projector'],
['📞','telephone receiver call'],['☎️','telephone'],['📠','fax machine'],
['📺','television tv'],['📻','radio'],['🎙️','studio microphone'],
['🧭','compass'],['⏱️','stopwatch'],['⏲️','timer clock'],
['⏰','alarm clock'],['🕰️','mantelpiece clock'],['⌛','hourglass done'],
['⏳','hourglass not done time'],['📡','satellite antenna'],
['🔋','battery'],['🪫','low battery'],['🔌','electric plug'],
['💡','light bulb idea'],['🔦','flashlight torch'],['🕯️','candle'],
['🧯','fire extinguisher'],['💸','money wings flying cash'],
['💵','dollar banknote money'],['💴','yen banknote money'],
['💶','euro banknote money'],['💷','pound banknote money'],
['🪙','coin money'],['💰','money bag cash'],['💳','credit card payment'],
['🧾','receipt bill'],['💹','chart increasing yen money'],
['✉️','envelope mail'],['📧','email'],['📨','incoming envelope mail'],
['📩','envelope arrow mail'],['📤','outbox tray'],['📥','inbox tray'],
['📦','package box'],['🏷️','label tag'],['📪','closed mailbox lowered flag'],
['📫','closed mailbox raised flag'],['📮','postbox'],['🗳️','ballot box'],
['✏️','pencil write'],['✒️','black nib pen'],['🖋️','fountain pen'],
['🖊️','pen'],['🖌️','paintbrush'],['🖍️','crayon'],['📝','memo note write'],
['💼','briefcase work'],['📁','file folder'],['📂','open file folder'],
['🗂️','card index dividers'],['📅','calendar date'],['📆','tear off calendar date'],
['🗒️','spiral notepad'],['🗓️','spiral calendar'],['📇','card index'],
['📈','chart increasing trend growth'],['📉','chart decreasing trend loss'],
['📊','bar chart statistics'],['📋','clipboard'],['📌','pushpin'],
['📍','round pushpin location'],['📎','paperclip'],['🖇️','linked paperclips'],
['📏','straight ruler'],['📐','triangular ruler'],['✂️','scissors cut'],
['🗃️','card file box'],['🗄️','file cabinet'],['🗑️','wastebasket trash'],
['🔒','locked padlock lock'],['🔓','unlocked padlock'],['🔐','locked key'],
['🔑','key'],['🗝️','old key'],['🔨','hammer tool'],['🪓','axe'],
['⛏️','pick tool'],['⚒️','hammer pick tools'],['🛠️','hammer wrench tools'],
['🗡️','dagger knife'],['⚔️','crossed swords'],
['🛡️','shield'],['🔧','wrench tool'],['🪛','screwdriver'],
['🔩','nut bolt'],['⚙️','gear settings'],['⚖️','balance scale justice'],
['🔗','link chain'],['⛓️','chains'],['🧰','toolbox'],['🧲','magnet'],
['🪜','ladder'],['⚗️','alembic science'],['🧪','test tube science'],
['🧬','dna science'],['🔬','microscope science'],['🔭','telescope science'],
['💊','pill medicine'],['💉','syringe injection'],['🩹','adhesive bandage'],
['🩺','stethoscope medical'],['🚪','door'],['🪞','mirror'],['🪟','window'],
['🛏️','bed sleep'],['🛋️','couch lamp sofa'],['🪑','chair seat'],
['🚽','toilet'],['🚿','shower'],['🛁','bathtub'],['🪒','razor shave'],
['🧴','lotion bottle'],['🧷','safety pin'],['🧹','broom clean'],
['🧺','basket'],['🧻','roll paper toilet'],['🪣','bucket'],
['🧼','soap bar'],['🪥','toothbrush'],['🧽','sponge'],
['🛒','shopping cart trolley'],['🚬','cigarette smoking'],
['⚰️','coffin death'],['🪦','headstone grave'],['⚱️','funeral urn'],
]},
{ cat: 'Symboler', items: [
['❤️','red heart love'],['🧡','orange heart'],['💛','yellow heart'],
['💚','green heart'],['💙','blue heart'],['💜','purple heart'],
['🖤','black heart'],['🤍','white heart'],['🤎','brown heart'],
['💔','broken heart'],['❣️','heart exclamation'],['💕','two hearts love'],
['💞','revolving hearts'],['💓','beating heart'],['💗','growing heart'],
['💖','sparkling heart'],['💘','heart arrow cupid'],['💝','heart ribbon gift'],
['💟','heart decoration'],['☮️','peace symbol'],['✝️','latin cross'],
['☪️','star crescent islam'],['🕉️','om hindu'],['☸️','wheel dharma buddhism'],
['✡️','star david judaism'],['☯️','yin yang'],['⛎','ophiuchus zodiac'],
['♈','aries zodiac'],['♉','taurus zodiac'],['♊','gemini zodiac'],
['♋','cancer zodiac'],['♌','leo zodiac'],['♍','virgo zodiac'],
['♎','libra zodiac'],['♏','scorpio zodiac'],['♐','sagittarius zodiac'],
['♑','capricorn zodiac'],['♒','aquarius zodiac'],['♓','pisces zodiac'],
['🆔','id button'],['⚛️','atom symbol'],['☢️','radioactive'],
['☣️','biohazard'],['💮','white flower'],['🆚','vs button'],
['🅰️','a button blood type'],['🅱️','b button blood type'],
['🆎','ab button blood type'],['🅾️','o button blood type'],
['🆘','sos help'],['❌','cross mark x wrong'],['⭕','hollow red circle'],
['🛑','stop sign'],['⛔','no entry'],['📛','name badge'],
['🚫','prohibited no'],['💯','hundred points 100 perfect'],
['💢','anger symbol'],['♨️','hot springs'],['🚭','no smoking'],
['❗','exclamation mark'],['❓','question mark'],['‼️','double exclamation mark'],
['⁉️','exclamation question mark'],['⚠️','warning'],['🚸','children crossing'],
['🔱','trident emblem'],['♻️','recycling symbol'],['✅','check mark button yes'],
['❇️','sparkle'],['✳️','eight spoked asterisk'],['❎','cross mark button'],
['🌐','globe meridians internet'],['💠','diamond dot'],['🌀','cyclone'],
['💤','zzz sleep'],['🏧','atm sign'],['♿','wheelchair symbol'],
['🅿️','p button parking'],['🚹','mens room'],['🚺','womens room'],
['🚻','restroom'],['🚮','litter bin'],['ℹ️','information'],
['🆗','ok button'],['🆕','new button'],['🆓','free button'],
['0️⃣','digit zero'],['1️⃣','digit one'],['2️⃣','digit two'],['3️⃣','digit three'],
['4️⃣','digit four'],['5️⃣','digit five'],['6️⃣','digit six'],['7️⃣','digit seven'],
['8️⃣','digit eight'],['9️⃣','digit nine'],['🔟','keycap ten'],
['🔢','input numbers'],['#️⃣','hash keycap'],['▶️','play button'],
['⏸️','pause button'],['⏹️','stop button'],['⏺️','record button'],
['⏭️','next track button'],['⏮️','last track button'],['⏩','fast forward'],
['⏪','fast reverse'],['◀️','reverse button'],['🔼','upwards button'],
['🔽','downwards button'],['➡️','right arrow'],['⬅️','left arrow'],
['⬆️','up arrow'],['⬇️','down arrow'],['↩️','right arrow curving left'],
['↪️','left arrow curving right'],['🔀','shuffle tracks button'],
['🔁','repeat button'],['🔄','counterclockwise arrows refresh reload'],
['🎵','musical note'],['🎶','musical notes'],['➕','plus sign'],
['➖','minus sign'],['➗','division sign'],['✖️','multiplication x sign'],
['♾️','infinity'],['💲','heavy dollar sign'],['💱','currency exchange'],
['™️','trade mark'],['©️','copyright'],['®️','registered'],
['🔚','end arrow'],['🔙','back arrow'],['🔛','on arrow'],
['🔝','top arrow'],['🔜','soon arrow'],['✔️','check mark'],
['☑️','check box button'],['🔘','radio button'],['🔴','red circle'],
['🟠','orange circle'],['🟡','yellow circle'],['🟢','green circle'],
['🔵','blue circle'],['🟣','purple circle'],['⚫','black circle'],
['⚪','white circle'],['🟤','brown circle'],['🔶','large orange diamond'],
['🔷','large blue diamond'],['🔸','small orange diamond'],
['🔹','small blue diamond'],['🔺','red triangle pointed up'],
['🔻','red triangle pointed down'],['🔲','black square button'],
['🔳','white square button'],['⬛','black large square'],
['⬜','white large square'],['🟥','red square'],['🟧','orange square'],
['🟨','yellow square'],['🟩','green square'],['🟦','blue square'],
['🟪','purple square'],['🟫','brown square'],
]},
{ cat: 'Flagg', items: [
['🏳️','white flag'],['🏴','black flag'],['🏁','checkered flag finish'],
['🚩','triangular flag'],['🏳️‍🌈','rainbow flag pride'],
['🏴‍☠️','pirate flag'],['🇳🇴','norway flag norwegian'],
['🇸🇪','sweden flag swedish'],['🇩🇰','denmark flag danish'],
['🇫🇮','finland flag finnish'],['🇮🇸','iceland flag icelandic'],
['🇬🇧','united kingdom flag uk british'],['🇺🇸','united states flag usa american'],
['🇩🇪','germany flag german'],['🇫🇷','france flag french'],
['🇪🇸','spain flag spanish'],['🇮🇹','italy flag italian'],
['🇳🇱','netherlands flag dutch'],['🇵🇱','poland flag polish'],
['🇵🇹','portugal flag portuguese'],['🇬🇷','greece flag greek'],
['🇹🇷','turkey flag turkish'],['🇷🇺','russia flag russian'],
['🇨🇳','china flag chinese'],['🇯🇵','japan flag japanese'],
['🇰🇷','south korea flag korean'],['🇮🇳','india flag indian'],
['🇧🇷','brazil flag brazilian'],['🇨🇦','canada flag canadian'],
['🇦🇺','australia flag australian'],['🇲🇽','mexico flag mexican'],
['🇪🇺','european union flag eu'],['🇨🇭','switzerland flag swiss'],
['🇦🇹','austria flag austrian'],['🇧🇪','belgium flag belgian'],
['🇮🇪','ireland flag irish'],['🇺🇦','ukraine flag ukrainian'],
['🇿🇦','south africa flag'],['🇹🇭','thailand flag thai'],
['🇻🇳','vietnam flag vietnamese'],
]},
];
